[package]
name = "rpass"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.0", features = ["derive"] }
serde_json = "1.0"
chacha20poly1305 = "0.10.0"
sha2 = "0.10.0"
rpassword = "7.3"
